package thostftdcuserapistruct;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
/**
 * \u5f53\u524d\u94f6\u671f\u6240\u5c5e\u4ea4\u6613\u4e2d\u5fc3<br>
 * <i>native declaration : F:\jna\ThostFtdcUserApiStruct.h:7607</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */

 
public class CThostFtdcCurrTransferIdentityField extends StructObject {
	public CThostFtdcCurrTransferIdentityField() {
		super();
	}
	/**
	 * \u4ea4\u6613\u4e2d\u5fc3\u4ee3\u7801<br>
	 * C type : TThostFtdcDRIdentityIDType
	 */
	@Field(0) 
	public int IdentityID() {
		return this.io.getIntField(this, 0);
	}
	/**
	 * \u4ea4\u6613\u4e2d\u5fc3\u4ee3\u7801<br>
	 * C type : TThostFtdcDRIdentityIDType
	 */
	@Field(0) 
	public CThostFtdcCurrTransferIdentityField IdentityID(int IdentityID) {
		this.io.setIntField(this, 0, IdentityID);
		return this;
	}

	@SuppressWarnings({ "rawtypes", "unchecked" })
	public CThostFtdcCurrTransferIdentityField(Pointer pointer) {
		super(pointer);
	}
}
