package thostftdcuserapistruct;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Array;
import org.bridj.ann.Field;
/**
 * \u67e5\u8be2\u5408\u7ea6<br>
 * <i>native declaration : F:\jna\ThostFtdcUserApiStruct.h:2397</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */

 
public class CThostFtdcQryInstrumentField extends StructObject {
	public CThostFtdcQryInstrumentField() {
		super();
	}
	/**
	 * \u5408\u7ea6\u4ee3\u7801<br>
	 * C type : TThostFtdcInstrumentIDType
	 */
	@Array({31}) 
	@Field(0) 
	public Pointer<Byte > InstrumentID() {
		return this.io.getPointerField(this, 0);
	}
	/**
	 * \u4ea4\u6613\u6240\u4ee3\u7801<br>
	 * C type : TThostFtdcExchangeIDType
	 */
	@Array({9}) 
	@Field(1) 
	public Pointer<Byte > ExchangeID() {
		return this.io.getPointerField(this, 1);
	}
	
	@Array({9})
    @Field(1)
    public void setExchangeID(String exchangeID) {
        this.io.getPointerField(this, 1).setCString(exchangeID);
    }

    public String getExchangeID() {
        return ExchangeID().getCString();
    }

	
	/**
	 * \u5408\u7ea6\u5728\u4ea4\u6613\u6240\u7684\u4ee3\u7801<br>
	 * C type : TThostFtdcExchangeInstIDType
	 */
	@Array({31}) 
	@Field(2) 
	public Pointer<Byte > ExchangeInstID() {
		return this.io.getPointerField(this, 2);
	}
	/**
	 * \u4ea7\u54c1\u4ee3\u7801<br>
	 * C type : TThostFtdcInstrumentIDType
	 */
	@Array({31}) 
	@Field(3) 
	public Pointer<Byte > ProductID() {
		return this.io.getPointerField(this, 3);
	}

	@SuppressWarnings({ "rawtypes", "unchecked" })
	public CThostFtdcQryInstrumentField(Pointer pointer) {
		super(pointer);
	}
}
