package thostftdcuserapistruct;

import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Array;
import org.bridj.ann.Field;

/**
 * \u7528\u6237\u767b\u5f55\u8bf7\u6c42<br>
 * <i>native declaration : F:\jna\ThostFtdcUserApiStruct.h:13</i><br>
 * This file was autogenerated by
 * <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that
 * <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a
 * few opensource projects.</a>.<br>
 * For help, please visit
 * <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or
 * <a href="http://bridj.googlecode.com/">BridJ</a> .
 */

public class CThostFtdcReqUserLoginField extends StructObject {
	public CThostFtdcReqUserLoginField() {
		super();
	}

	/**
	 * \u4ea4\u6613\u65e5<br>
	 * C type : TThostFtdcDateType
	 */
	@Array({ 9 })
	@Field(0)
	public Pointer<Byte> TradingDay() {
		return this.io.getPointerField(this, 0);
	}

	/**
	 * \u7ecf\u7eaa\u516c\u53f8\u4ee3\u7801<br>
	 * C type : TThostFtdcBrokerIDType
	 */
	@Array({ 11 })
	@Field(1)
	public Pointer<Byte> BrokerID() {
		return this.io.getPointerField(this, 1);
	}

	@Array({ 11 })
	@Field(1)
	public void setBrokerID(String brokerID) {
		this.io.getPointerField(this, 1).setCString(brokerID);
	}

	public String getBrokerID() {
		return BrokerID().getCString();
	}

	/**
	 * \u7528\u6237\u4ee3\u7801<br>
	 * C type : TThostFtdcUserIDType
	 */
	@Array({ 16 })
	@Field(2)
	public Pointer<Byte> UserID() {
		return this.io.getPointerField(this, 2);
	}

	/**
	 * \u5bc6\u7801<br>
	 * C type : TThostFtdcPasswordType
	 */
	@Array({ 41 })
	@Field(3)
	public Pointer<Byte> Password() {
		return this.io.getPointerField(this, 3);
	}

	@Array({ 41 })
	@Field(3)
	public void setPassword(String password) {
		this.io.getPointerField(this, 3).setCString(password);
	}

	public String getPassword() {
		return Password().getCString();
	}

	/**
	 * \u7528\u6237\u7aef\u4ea7\u54c1\u4fe1\u606f<br>
	 * C type : TThostFtdcProductInfoType
	 */
	@Array({ 11 })
	@Field(4)
	public Pointer<Byte> UserProductInfo() {
		return this.io.getPointerField(this, 4);
	}

	/**
	 * \u63a5\u53e3\u7aef\u4ea7\u54c1\u4fe1\u606f<br>
	 * C type : TThostFtdcProductInfoType
	 */
	@Array({ 11 })
	@Field(5)
	public Pointer<Byte> InterfaceProductInfo() {
		return this.io.getPointerField(this, 5);
	}

	/**
	 * \u534f\u8bae\u4fe1\u606f<br>
	 * C type : TThostFtdcProtocolInfoType
	 */
	@Array({ 11 })
	@Field(6)
	public Pointer<Byte> ProtocolInfo() {
		return this.io.getPointerField(this, 6);
	}

	/**
	 * Mac\u5730\u5740<br>
	 * C type : TThostFtdcMacAddressType
	 */
	@Array({ 21 })
	@Field(7)
	public Pointer<Byte> MacAddress() {
		return this.io.getPointerField(this, 7);
	}

	/**
	 * \u52a8\u6001\u5bc6\u7801<br>
	 * C type : TThostFtdcPasswordType
	 */
	@Array({ 41 })
	@Field(8)
	public Pointer<Byte> OneTimePassword() {
		return this.io.getPointerField(this, 8);
	}

	/**
	 * \u7ec8\u7aefIP\u5730\u5740<br>
	 * C type : TThostFtdcIPAddressType
	 */
	@Array({ 16 })
	@Field(9)
	public Pointer<Byte> ClientIPAddress() {
		return this.io.getPointerField(this, 9);
	}

	@Array({ 16 })
	@Field(2)
	public void setUserID(String userID) {
		this.io.getPointerField(this, 2).setCString(userID);
	}

	@SuppressWarnings({ "rawtypes", "unchecked" })
	public CThostFtdcReqUserLoginField(Pointer pointer) {
		super(pointer);
	}
}
